In [1]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataNoDefOW_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_NoDef.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_NoDef.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_NoDef.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_NoDef.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataNoDefOW_Training()


/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Loading non-defended dataset for open-world scenario for training


X_train loaded
y_train loaded


X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)


Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False


Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 ...
 [ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 [-1.  1.  1. ... -1. -1. -1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]


********for 20 epoch****

In [2]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ELU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataNoDefOW_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_NoDef.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_NoDef.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_NoDef.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_NoDef.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataNoDefOW_Training()


Loading non-defended dataset for open-world scenario for training


X_train loaded
y_train loaded


X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)


Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False


Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 ...
 [ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 [-1.  1.  1. ... -1. -1. -1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]


In [3]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.3, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataNoDefOW_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


    # Compile the model
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs=20, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
   


    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
saved_path_keras = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
model.save(saved_path_keras)

print("Trained model saved successfully at:", saved_path_keras)


Model built successfully.
Model Summary:
Model: "sequential"


_________________________________________________________________


 Layer (type)                Output Shape              Param #   


 block1_conv1 (Conv1D)       (None, 5000, 32)          288       


 batch_normalization_1 (Bat  (None, 5000, 32)          128       


 chNormalization)                                                


 block1_adv_act1 (Activatio  (None, 5000, 32)          0         


 n)                                                              


 block1_conv2 (Conv1D)       (None, 5000, 32)          8224      


 batch_normalization_2 (Bat  (None, 5000, 32)          128       


 chNormalization)                                                


 block1_adv_act2 (Activatio  (None, 5000, 32)          0         


 n)                                                              


 block1_pool (MaxPooling1D)  (None, 1250, 32)          0         


 block1_dropout (Dropout)    (None, 1250, 32)          0         


 block2_conv1 (Conv1D)       (None, 1250, 64)          16448     


 batch_normalization_3 (Bat  (None, 1250, 64)          256       


 chNormalization)                                                


 block2_adv_act1 (Activatio  (None, 1250, 64)          0         


 n)                                                              


 block2_conv2 (Conv1D)       (None, 1250, 64)          32832     


 batch_normalization_4 (Bat  (None, 1250, 64)          256       


 chNormalization)                                                


 block2_adv_act2 (Activatio  (None, 1250, 64)          0         


 n)                                                              


 block2_pool (MaxPooling1D)  (None, 313, 64)           0         


 block2_dropout (Dropout)    (None, 313, 64)           0         


 block3_conv1 (Conv1D)       (None, 313, 128)          65664     


 batch_normalization_5 (Bat  (None, 313, 128)          512       


 chNormalization)                                                


 block3_adv_act1 (Activatio  (None, 313, 128)          0         


 n)                                                              


 block3_conv2 (Conv1D)       (None, 313, 128)          131200    


 batch_normalization_6 (Bat  (None, 313, 128)          512       


 chNormalization)                                                


 block3_adv_act2 (Activatio  (None, 313, 128)          0         


 n)                                                              


 block3_pool (MaxPooling1D)  (None, 79, 128)           0         


 block3_dropout (Dropout)    (None, 79, 128)           0         


 flatten (Flatten)           (None, 10112)             0         


 fc1 (Dense)                 (None, 512)               5177856   


 batch_normalization_9 (Bat  (None, 512)               2048      


 chNormalization)                                                


 fc1_act (Activation)        (None, 512)               0         


 fc1_dropout (Dropout)       (None, 512)               0         


 fc2 (Dense)                 (None, 512)               262656    


 batch_normalization_10 (Ba  (None, 512)               2048      


 tchNormalization)                                               


 fc2_act (Activation)        (None, 512)               0         


 fc2_dropout (Dropout)       (None, 512)               0         


 fc_final (Dense)            (None, 96)                49248     


 softmax (Activation)        (None, 96)                0         


Total params: 5750304 (21.94 MB)


Trainable params: 5747360 (21.92 MB)


Non-trainable params: 2944 (11.50 KB)


_________________________________________________________________


Loading non-defended dataset for open-world scenario for training


X_train loaded
y_train loaded


X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)


Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False


Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 ...
 [ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 [-1.  1.  1. ... -1. -1. -1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]

Training on Fold 1/5


Model built successfully.


Epoch 1/20


1320/1320 - 94s - loss: 0.8560 - accuracy: 0.7812 - val_loss: 0.3020 - val_accuracy: 0.9202 - 94s/epoch - 72ms/step


Epoch 2/20


1320/1320 - 85s - loss: 0.3320 - accuracy: 0.9111 - val_loss: 0.2216 - val_accuracy: 0.9424 - 85s/epoch - 64ms/step


Epoch 3/20


1320/1320 - 85s - loss: 0.2533 - accuracy: 0.9309 - val_loss: 0.1995 - val_accuracy: 0.9457 - 85s/epoch - 65ms/step


Epoch 4/20


1320/1320 - 85s - loss: 0.2107 - accuracy: 0.9410 - val_loss: 0.1836 - val_accuracy: 0.9525 - 85s/epoch - 65ms/step


Epoch 5/20


1320/1320 - 85s - loss: 0.1810 - accuracy: 0.9488 - val_loss: 0.1650 - val_accuracy: 0.9552 - 85s/epoch - 65ms/step


Epoch 6/20


1320/1320 - 85s - loss: 0.1583 - accuracy: 0.9550 - val_loss: 0.1601 - val_accuracy: 0.9574 - 85s/epoch - 65ms/step


Epoch 7/20


1320/1320 - 85s - loss: 0.1386 - accuracy: 0.9601 - val_loss: 0.1517 - val_accuracy: 0.9611 - 85s/epoch - 65ms/step


Epoch 8/20


1320/1320 - 85s - loss: 0.1305 - accuracy: 0.9626 - val_loss: 0.1591 - val_accuracy: 0.9630 - 85s/epoch - 65ms/step


Epoch 9/20


1320/1320 - 85s - loss: 0.1160 - accuracy: 0.9663 - val_loss: 0.1644 - val_accuracy: 0.9581 - 85s/epoch - 64ms/step


Epoch 10/20


1320/1320 - 85s - loss: 0.1091 - accuracy: 0.9679 - val_loss: 0.1478 - val_accuracy: 0.9619 - 85s/epoch - 65ms/step


Epoch 11/20


1320/1320 - 85s - loss: 0.1028 - accuracy: 0.9700 - val_loss: 0.1573 - val_accuracy: 0.9617 - 85s/epoch - 64ms/step


Epoch 12/20


1320/1320 - 85s - loss: 0.0984 - accuracy: 0.9717 - val_loss: 0.1481 - val_accuracy: 0.9637 - 85s/epoch - 65ms/step


Epoch 13/20


1320/1320 - 85s - loss: 0.0876 - accuracy: 0.9748 - val_loss: 0.1629 - val_accuracy: 0.9612 - 85s/epoch - 64ms/step


Epoch 14/20


1320/1320 - 85s - loss: 0.0851 - accuracy: 0.9759 - val_loss: 0.1459 - val_accuracy: 0.9665 - 85s/epoch - 64ms/step


Epoch 15/20


1320/1320 - 85s - loss: 0.0822 - accuracy: 0.9754 - val_loss: 0.1446 - val_accuracy: 0.9656 - 85s/epoch - 64ms/step


Epoch 16/20


1320/1320 - 85s - loss: 0.0798 - accuracy: 0.9771 - val_loss: 0.1479 - val_accuracy: 0.9653 - 85s/epoch - 64ms/step


Epoch 17/20


1320/1320 - 85s - loss: 0.0760 - accuracy: 0.9782 - val_loss: 0.1428 - val_accuracy: 0.9679 - 85s/epoch - 65ms/step


Epoch 18/20


1320/1320 - 85s - loss: 0.0735 - accuracy: 0.9782 - val_loss: 0.1381 - val_accuracy: 0.9683 - 85s/epoch - 65ms/step


Epoch 19/20


1320/1320 - 85s - loss: 0.0687 - accuracy: 0.9805 - val_loss: 0.1350 - val_accuracy: 0.9681 - 85s/epoch - 64ms/step


Epoch 20/20


1320/1320 - 85s - loss: 0.0655 - accuracy: 0.9810 - val_loss: 0.1545 - val_accuracy: 0.9677 - 85s/epoch - 64ms/step


660/660 - 6s - loss: 0.1545 - accuracy: 0.9677 - 6s/epoch - 10ms/step



Fold 1 - Test Accuracy: 96.77%

Training on Fold 2/5


Model built successfully.


Epoch 1/20


1320/1320 - 92s - loss: 0.8508 - accuracy: 0.7831 - val_loss: 0.3562 - val_accuracy: 0.9011 - 92s/epoch - 70ms/step


Epoch 2/20


1320/1320 - 85s - loss: 0.3357 - accuracy: 0.9108 - val_loss: 0.2589 - val_accuracy: 0.9290 - 85s/epoch - 65ms/step


Epoch 3/20


1320/1320 - 85s - loss: 0.2502 - accuracy: 0.9322 - val_loss: 0.1862 - val_accuracy: 0.9491 - 85s/epoch - 65ms/step


Epoch 4/20


1320/1320 - 85s - loss: 0.2118 - accuracy: 0.9404 - val_loss: 0.1661 - val_accuracy: 0.9556 - 85s/epoch - 65ms/step


Epoch 5/20


1320/1320 - 85s - loss: 0.1830 - accuracy: 0.9477 - val_loss: 0.1758 - val_accuracy: 0.9513 - 85s/epoch - 65ms/step


Epoch 6/20


1320/1320 - 85s - loss: 0.1584 - accuracy: 0.9553 - val_loss: 0.1600 - val_accuracy: 0.9574 - 85s/epoch - 65ms/step


Epoch 7/20


1320/1320 - 85s - loss: 0.1419 - accuracy: 0.9594 - val_loss: 0.1588 - val_accuracy: 0.9581 - 85s/epoch - 65ms/step


Epoch 8/20


1320/1320 - 85s - loss: 0.1278 - accuracy: 0.9637 - val_loss: 0.1381 - val_accuracy: 0.9635 - 85s/epoch - 65ms/step


Epoch 9/20


1320/1320 - 85s - loss: 0.1195 - accuracy: 0.9662 - val_loss: 0.1438 - val_accuracy: 0.9635 - 85s/epoch - 65ms/step


Epoch 10/20


1320/1320 - 85s - loss: 0.1110 - accuracy: 0.9685 - val_loss: 0.1553 - val_accuracy: 0.9608 - 85s/epoch - 65ms/step


Epoch 11/20


1320/1320 - 85s - loss: 0.1041 - accuracy: 0.9700 - val_loss: 0.1420 - val_accuracy: 0.9648 - 85s/epoch - 65ms/step


Epoch 12/20


1320/1320 - 85s - loss: 0.1012 - accuracy: 0.9710 - val_loss: 0.1645 - val_accuracy: 0.9553 - 85s/epoch - 65ms/step


Epoch 13/20


1320/1320 - 85s - loss: 0.0878 - accuracy: 0.9748 - val_loss: 0.1481 - val_accuracy: 0.9616 - 85s/epoch - 65ms/step


Epoch 14/20


1320/1320 - 85s - loss: 0.0862 - accuracy: 0.9751 - val_loss: 0.1588 - val_accuracy: 0.9592 - 85s/epoch - 65ms/step


Epoch 15/20


1320/1320 - 85s - loss: 0.0844 - accuracy: 0.9756 - val_loss: 0.1416 - val_accuracy: 0.9648 - 85s/epoch - 65ms/step


Epoch 16/20


1320/1320 - 85s - loss: 0.0779 - accuracy: 0.9773 - val_loss: 0.1434 - val_accuracy: 0.9644 - 85s/epoch - 65ms/step


Epoch 17/20


1320/1320 - 85s - loss: 0.0739 - accuracy: 0.9787 - val_loss: 0.1645 - val_accuracy: 0.9604 - 85s/epoch - 65ms/step


Epoch 18/20


1320/1320 - 85s - loss: 0.0747 - accuracy: 0.9790 - val_loss: 0.1352 - val_accuracy: 0.9673 - 85s/epoch - 65ms/step


Epoch 19/20


1320/1320 - 85s - loss: 0.0704 - accuracy: 0.9796 - val_loss: 0.1409 - val_accuracy: 0.9674 - 85s/epoch - 65ms/step


Epoch 20/20


1320/1320 - 85s - loss: 0.0646 - accuracy: 0.9812 - val_loss: 0.1323 - val_accuracy: 0.9686 - 85s/epoch - 65ms/step


660/660 - 6s - loss: 0.1323 - accuracy: 0.9686 - 6s/epoch - 9ms/step



Fold 2 - Test Accuracy: 96.86%

Training on Fold 3/5


Model built successfully.


Epoch 1/20


1320/1320 - 92s - loss: 0.8468 - accuracy: 0.7844 - val_loss: 0.3214 - val_accuracy: 0.9136 - 92s/epoch - 70ms/step


Epoch 2/20


1320/1320 - 85s - loss: 0.3374 - accuracy: 0.9088 - val_loss: 0.2608 - val_accuracy: 0.9255 - 85s/epoch - 65ms/step


Epoch 3/20


1320/1320 - 85s - loss: 0.2524 - accuracy: 0.9307 - val_loss: 0.1736 - val_accuracy: 0.9537 - 85s/epoch - 64ms/step


Epoch 4/20


1320/1320 - 85s - loss: 0.2144 - accuracy: 0.9399 - val_loss: 0.1614 - val_accuracy: 0.9563 - 85s/epoch - 65ms/step


Epoch 5/20


1320/1320 - 85s - loss: 0.1828 - accuracy: 0.9487 - val_loss: 0.1578 - val_accuracy: 0.9561 - 85s/epoch - 64ms/step


Epoch 6/20


1320/1320 - 85s - loss: 0.1618 - accuracy: 0.9542 - val_loss: 0.1589 - val_accuracy: 0.9573 - 85s/epoch - 64ms/step


Epoch 7/20


1320/1320 - 85s - loss: 0.1451 - accuracy: 0.9590 - val_loss: 0.1299 - val_accuracy: 0.9651 - 85s/epoch - 64ms/step


Epoch 8/20


1320/1320 - 85s - loss: 0.1297 - accuracy: 0.9630 - val_loss: 0.1532 - val_accuracy: 0.9589 - 85s/epoch - 64ms/step


Epoch 9/20


1320/1320 - 85s - loss: 0.1221 - accuracy: 0.9648 - val_loss: 0.1356 - val_accuracy: 0.9651 - 85s/epoch - 64ms/step


Epoch 10/20


1320/1320 - 85s - loss: 0.1104 - accuracy: 0.9678 - val_loss: 0.1428 - val_accuracy: 0.9622 - 85s/epoch - 64ms/step


Epoch 11/20


1320/1320 - 85s - loss: 0.1059 - accuracy: 0.9692 - val_loss: 0.1391 - val_accuracy: 0.9637 - 85s/epoch - 65ms/step


Epoch 12/20


1320/1320 - 85s - loss: 0.0969 - accuracy: 0.9721 - val_loss: 0.1327 - val_accuracy: 0.9659 - 85s/epoch - 65ms/step


Epoch 13/20


1320/1320 - 85s - loss: 0.0900 - accuracy: 0.9737 - val_loss: 0.1391 - val_accuracy: 0.9647 - 85s/epoch - 64ms/step


Epoch 14/20


1320/1320 - 85s - loss: 0.0892 - accuracy: 0.9744 - val_loss: 0.1305 - val_accuracy: 0.9680 - 85s/epoch - 64ms/step


Epoch 15/20


1320/1320 - 85s - loss: 0.0828 - accuracy: 0.9762 - val_loss: 0.1393 - val_accuracy: 0.9660 - 85s/epoch - 64ms/step


Epoch 16/20


1320/1320 - 85s - loss: 0.0802 - accuracy: 0.9767 - val_loss: 0.1309 - val_accuracy: 0.9689 - 85s/epoch - 64ms/step


Epoch 17/20


1320/1320 - 85s - loss: 0.0782 - accuracy: 0.9775 - val_loss: 0.1188 - val_accuracy: 0.9704 - 85s/epoch - 64ms/step


Epoch 18/20


1320/1320 - 85s - loss: 0.0731 - accuracy: 0.9790 - val_loss: 0.1415 - val_accuracy: 0.9648 - 85s/epoch - 64ms/step


Epoch 19/20


1320/1320 - 85s - loss: 0.0709 - accuracy: 0.9800 - val_loss: 0.1265 - val_accuracy: 0.9690 - 85s/epoch - 64ms/step


Epoch 20/20


1320/1320 - 85s - loss: 0.0690 - accuracy: 0.9799 - val_loss: 0.1257 - val_accuracy: 0.9705 - 85s/epoch - 64ms/step


660/660 - 6s - loss: 0.1257 - accuracy: 0.9705 - 6s/epoch - 10ms/step



Fold 3 - Test Accuracy: 97.05%

Training on Fold 4/5


Model built successfully.


Epoch 1/20


1320/1320 - 93s - loss: 0.8498 - accuracy: 0.7852 - val_loss: 0.3087 - val_accuracy: 0.9191 - 93s/epoch - 70ms/step


Epoch 2/20


1320/1320 - 85s - loss: 0.3376 - accuracy: 0.9095 - val_loss: 0.2468 - val_accuracy: 0.9334 - 85s/epoch - 65ms/step


Epoch 3/20


1320/1320 - 85s - loss: 0.2627 - accuracy: 0.9285 - val_loss: 0.1882 - val_accuracy: 0.9491 - 85s/epoch - 65ms/step


Epoch 4/20


1320/1320 - 85s - loss: 0.2153 - accuracy: 0.9398 - val_loss: 0.1668 - val_accuracy: 0.9557 - 85s/epoch - 65ms/step


Epoch 5/20


1320/1320 - 85s - loss: 0.1862 - accuracy: 0.9472 - val_loss: 0.1870 - val_accuracy: 0.9500 - 85s/epoch - 65ms/step


Epoch 6/20


1320/1320 - 85s - loss: 0.1629 - accuracy: 0.9541 - val_loss: 0.1832 - val_accuracy: 0.9516 - 85s/epoch - 65ms/step


Epoch 7/20


1320/1320 - 85s - loss: 0.1496 - accuracy: 0.9569 - val_loss: 0.1594 - val_accuracy: 0.9567 - 85s/epoch - 65ms/step


Epoch 8/20


1320/1320 - 85s - loss: 0.1348 - accuracy: 0.9616 - val_loss: 0.1698 - val_accuracy: 0.9590 - 85s/epoch - 65ms/step


Epoch 9/20


1320/1320 - 85s - loss: 0.1194 - accuracy: 0.9655 - val_loss: 0.1475 - val_accuracy: 0.9621 - 85s/epoch - 65ms/step


Epoch 10/20


1320/1320 - 85s - loss: 0.1146 - accuracy: 0.9669 - val_loss: 0.1468 - val_accuracy: 0.9624 - 85s/epoch - 65ms/step


Epoch 11/20


1320/1320 - 85s - loss: 0.1061 - accuracy: 0.9691 - val_loss: 0.1377 - val_accuracy: 0.9645 - 85s/epoch - 65ms/step


Epoch 12/20


1320/1320 - 85s - loss: 0.0995 - accuracy: 0.9718 - val_loss: 0.1549 - val_accuracy: 0.9611 - 85s/epoch - 65ms/step


Epoch 13/20


1320/1320 - 85s - loss: 0.0938 - accuracy: 0.9724 - val_loss: 0.1290 - val_accuracy: 0.9683 - 85s/epoch - 65ms/step


Epoch 14/20


1320/1320 - 85s - loss: 0.0881 - accuracy: 0.9739 - val_loss: 0.1336 - val_accuracy: 0.9686 - 85s/epoch - 65ms/step


Epoch 15/20


1320/1320 - 85s - loss: 0.0842 - accuracy: 0.9754 - val_loss: 0.1251 - val_accuracy: 0.9699 - 85s/epoch - 65ms/step


Epoch 16/20


1320/1320 - 85s - loss: 0.0813 - accuracy: 0.9764 - val_loss: 0.1484 - val_accuracy: 0.9625 - 85s/epoch - 65ms/step


Epoch 17/20


1320/1320 - 85s - loss: 0.0747 - accuracy: 0.9780 - val_loss: 0.1401 - val_accuracy: 0.9676 - 85s/epoch - 65ms/step


Epoch 18/20


1320/1320 - 85s - loss: 0.0769 - accuracy: 0.9777 - val_loss: 0.1378 - val_accuracy: 0.9687 - 85s/epoch - 65ms/step


Epoch 19/20


1320/1320 - 85s - loss: 0.0721 - accuracy: 0.9797 - val_loss: 0.1332 - val_accuracy: 0.9689 - 85s/epoch - 65ms/step


Epoch 20/20


1320/1320 - 85s - loss: 0.0691 - accuracy: 0.9800 - val_loss: 0.1369 - val_accuracy: 0.9686 - 85s/epoch - 65ms/step


660/660 - 6s - loss: 0.1369 - accuracy: 0.9686 - 6s/epoch - 10ms/step



Fold 4 - Test Accuracy: 96.86%

Training on Fold 5/5


Model built successfully.


Epoch 1/20


1320/1320 - 93s - loss: 0.8549 - accuracy: 0.7801 - val_loss: 0.2934 - val_accuracy: 0.9230 - 93s/epoch - 70ms/step


Epoch 2/20


1320/1320 - 85s - loss: 0.3394 - accuracy: 0.9097 - val_loss: 0.2343 - val_accuracy: 0.9377 - 85s/epoch - 65ms/step


Epoch 3/20


1320/1320 - 85s - loss: 0.2579 - accuracy: 0.9292 - val_loss: 0.1868 - val_accuracy: 0.9510 - 85s/epoch - 65ms/step


Epoch 4/20


1320/1320 - 85s - loss: 0.2145 - accuracy: 0.9406 - val_loss: 0.1966 - val_accuracy: 0.9473 - 85s/epoch - 65ms/step


Epoch 5/20


1320/1320 - 85s - loss: 0.1859 - accuracy: 0.9478 - val_loss: 0.1607 - val_accuracy: 0.9571 - 85s/epoch - 65ms/step


Epoch 6/20


1320/1320 - 85s - loss: 0.1636 - accuracy: 0.9531 - val_loss: 0.1564 - val_accuracy: 0.9586 - 85s/epoch - 65ms/step


Epoch 7/20


1320/1320 - 85s - loss: 0.1423 - accuracy: 0.9591 - val_loss: 0.1592 - val_accuracy: 0.9592 - 85s/epoch - 65ms/step


Epoch 8/20


1320/1320 - 85s - loss: 0.1303 - accuracy: 0.9623 - val_loss: 0.1471 - val_accuracy: 0.9620 - 85s/epoch - 65ms/step


Epoch 9/20


1320/1320 - 85s - loss: 0.1217 - accuracy: 0.9641 - val_loss: 0.1641 - val_accuracy: 0.9600 - 85s/epoch - 65ms/step


Epoch 10/20


1320/1320 - 85s - loss: 0.1117 - accuracy: 0.9674 - val_loss: 0.1517 - val_accuracy: 0.9618 - 85s/epoch - 65ms/step


Epoch 11/20


1320/1320 - 85s - loss: 0.1059 - accuracy: 0.9698 - val_loss: 0.1482 - val_accuracy: 0.9635 - 85s/epoch - 65ms/step


Epoch 12/20


1320/1320 - 85s - loss: 0.0995 - accuracy: 0.9712 - val_loss: 0.1532 - val_accuracy: 0.9624 - 85s/epoch - 65ms/step


Epoch 13/20


1320/1320 - 85s - loss: 0.0946 - accuracy: 0.9728 - val_loss: 0.1524 - val_accuracy: 0.9639 - 85s/epoch - 65ms/step


Epoch 14/20


1320/1320 - 85s - loss: 0.0880 - accuracy: 0.9744 - val_loss: 0.1458 - val_accuracy: 0.9642 - 85s/epoch - 65ms/step


Epoch 15/20


1320/1320 - 85s - loss: 0.0821 - accuracy: 0.9764 - val_loss: 0.1373 - val_accuracy: 0.9665 - 85s/epoch - 65ms/step


Epoch 16/20


1320/1320 - 85s - loss: 0.0789 - accuracy: 0.9767 - val_loss: 0.1442 - val_accuracy: 0.9652 - 85s/epoch - 65ms/step


Epoch 17/20


1320/1320 - 85s - loss: 0.0745 - accuracy: 0.9783 - val_loss: 0.1464 - val_accuracy: 0.9677 - 85s/epoch - 65ms/step


Epoch 18/20


1320/1320 - 85s - loss: 0.0752 - accuracy: 0.9776 - val_loss: 0.1605 - val_accuracy: 0.9657 - 85s/epoch - 65ms/step


Epoch 19/20


1320/1320 - 85s - loss: 0.0714 - accuracy: 0.9791 - val_loss: 0.1406 - val_accuracy: 0.9688 - 85s/epoch - 65ms/step


Epoch 20/20


1320/1320 - 85s - loss: 0.0700 - accuracy: 0.9795 - val_loss: 0.1511 - val_accuracy: 0.9658 - 85s/epoch - 65ms/step


660/660 - 6s - loss: 0.1511 - accuracy: 0.9658 - 6s/epoch - 9ms/step



Fold 5 - Test Accuracy: 96.58%


Trained model saved successfully at: /kaggle/working/DFNet_OpenWorld_NoDef.keras


In [4]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.5, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataNoDefOW_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


    # Compile the model
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs=25, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
   


    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
saved_path_keras = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
model.save(saved_path_keras)

print("Trained model saved successfully at:", saved_path_keras)


Model built successfully.
Model Summary:
Model: "sequential_6"


_________________________________________________________________


 Layer (type)                Output Shape              Param #   


 block1_conv1 (Conv1D)       (None, 5000, 32)          288       


 batch_normalization_1 (Bat  (None, 5000, 32)          128       


 chNormalization)                                                


 block1_adv_act1 (Activatio  (None, 5000, 32)          0         


 n)                                                              


 block1_conv2 (Conv1D)       (None, 5000, 32)          8224      


 batch_normalization_2 (Bat  (None, 5000, 32)          128       


 chNormalization)                                                


 block1_adv_act2 (Activatio  (None, 5000, 32)          0         


 n)                                                              


 block1_pool (MaxPooling1D)  (None, 1250, 32)          0         


 block1_dropout (Dropout)    (None, 1250, 32)          0         


 block2_conv1 (Conv1D)       (None, 1250, 64)          16448     


 batch_normalization_3 (Bat  (None, 1250, 64)          256       


 chNormalization)                                                


 block2_adv_act1 (Activatio  (None, 1250, 64)          0         


 n)                                                              


 block2_conv2 (Conv1D)       (None, 1250, 64)          32832     


 batch_normalization_4 (Bat  (None, 1250, 64)          256       


 chNormalization)                                                


 block2_adv_act2 (Activatio  (None, 1250, 64)          0         


 n)                                                              


 block2_pool (MaxPooling1D)  (None, 313, 64)           0         


 block2_dropout (Dropout)    (None, 313, 64)           0         


 block3_conv1 (Conv1D)       (None, 313, 128)          65664     


 batch_normalization_5 (Bat  (None, 313, 128)          512       


 chNormalization)                                                


 block3_adv_act1 (Activatio  (None, 313, 128)          0         


 n)                                                              


 block3_conv2 (Conv1D)       (None, 313, 128)          131200    


 batch_normalization_6 (Bat  (None, 313, 128)          512       


 chNormalization)                                                


 block3_adv_act2 (Activatio  (None, 313, 128)          0         


 n)                                                              


 block3_pool (MaxPooling1D)  (None, 79, 128)           0         


 block3_dropout (Dropout)    (None, 79, 128)           0         


 flatten (Flatten)           (None, 10112)             0         


 fc1 (Dense)                 (None, 512)               5177856   


 batch_normalization_9 (Bat  (None, 512)               2048      


 chNormalization)                                                


 fc1_act (Activation)        (None, 512)               0         


 fc1_dropout (Dropout)       (None, 512)               0         


 fc2 (Dense)                 (None, 512)               262656    


 batch_normalization_10 (Ba  (None, 512)               2048      


 tchNormalization)                                               


 fc2_act (Activation)        (None, 512)               0         


 fc2_dropout (Dropout)       (None, 512)               0         


 fc_final (Dense)            (None, 96)                49248     


 softmax (Activation)        (None, 96)                0         


Total params: 5750304 (21.94 MB)


Trainable params: 5747360 (21.92 MB)


Non-trainable params: 2944 (11.50 KB)


_________________________________________________________________


Loading non-defended dataset for open-world scenario for training


X_train loaded
y_train loaded


X_valid loaded
y_valid loaded
Data dimensions:
X: Training data's shape :  (96000, 5000)
y: Training data's shape :  (96000,)
X: Validation data's shape :  (9600, 5000)
y: Validation data's shape :  (9600,)


Any None values in X_train: False
Any None values in y_train: False
Any None values in X_valid: False
Any None values in y_valid: False


Merged data dimensions:
X: Merged data's shape :  (105600, 5000)
y: Merged data's shape :  (105600,)
Features of the merged dataset:
[[-1. -1.  1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 [-1.  1. -1. ...  0.  0.  0.]
 ...
 [ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]
 [-1.  1.  1. ... -1. -1. -1.]]
Features of the merged dataset:
[80 83 95 ... 95 34 44]

Training on Fold 1/5


Model built successfully.


Epoch 1/25


1320/1320 - 93s - loss: 0.8471 - accuracy: 0.7827 - val_loss: 0.3012 - val_accuracy: 0.9207 - 93s/epoch - 70ms/step


Epoch 2/25


1320/1320 - 85s - loss: 0.3362 - accuracy: 0.9086 - val_loss: 0.2350 - val_accuracy: 0.9384 - 85s/epoch - 65ms/step


Epoch 3/25


1320/1320 - 85s - loss: 0.2587 - accuracy: 0.9294 - val_loss: 0.2384 - val_accuracy: 0.9358 - 85s/epoch - 65ms/step


Epoch 4/25


1320/1320 - 85s - loss: 0.2160 - accuracy: 0.9396 - val_loss: 0.1891 - val_accuracy: 0.9512 - 85s/epoch - 65ms/step


Epoch 5/25


1320/1320 - 85s - loss: 0.1856 - accuracy: 0.9475 - val_loss: 0.1750 - val_accuracy: 0.9542 - 85s/epoch - 65ms/step


Epoch 6/25


1320/1320 - 85s - loss: 0.1637 - accuracy: 0.9542 - val_loss: 0.1764 - val_accuracy: 0.9550 - 85s/epoch - 65ms/step


Epoch 7/25


1320/1320 - 85s - loss: 0.1465 - accuracy: 0.9578 - val_loss: 0.1689 - val_accuracy: 0.9568 - 85s/epoch - 65ms/step


Epoch 8/25


1320/1320 - 85s - loss: 0.1383 - accuracy: 0.9597 - val_loss: 0.1607 - val_accuracy: 0.9582 - 85s/epoch - 65ms/step


Epoch 9/25


1320/1320 - 85s - loss: 0.1236 - accuracy: 0.9639 - val_loss: 0.1516 - val_accuracy: 0.9620 - 85s/epoch - 65ms/step


Epoch 10/25


1320/1320 - 85s - loss: 0.1129 - accuracy: 0.9673 - val_loss: 0.1489 - val_accuracy: 0.9609 - 85s/epoch - 65ms/step


Epoch 11/25


1320/1320 - 85s - loss: 0.1050 - accuracy: 0.9696 - val_loss: 0.1786 - val_accuracy: 0.9564 - 85s/epoch - 65ms/step


Epoch 12/25


1320/1320 - 85s - loss: 0.0986 - accuracy: 0.9718 - val_loss: 0.1564 - val_accuracy: 0.9596 - 85s/epoch - 65ms/step


Epoch 13/25


1320/1320 - 85s - loss: 0.0926 - accuracy: 0.9729 - val_loss: 0.1347 - val_accuracy: 0.9670 - 85s/epoch - 65ms/step


Epoch 14/25


1320/1320 - 85s - loss: 0.0901 - accuracy: 0.9746 - val_loss: 0.1435 - val_accuracy: 0.9649 - 85s/epoch - 65ms/step


Epoch 15/25


1320/1320 - 85s - loss: 0.0853 - accuracy: 0.9749 - val_loss: 0.1366 - val_accuracy: 0.9668 - 85s/epoch - 65ms/step


Epoch 16/25


1320/1320 - 85s - loss: 0.0813 - accuracy: 0.9765 - val_loss: 0.1472 - val_accuracy: 0.9652 - 85s/epoch - 65ms/step


Epoch 17/25


1320/1320 - 85s - loss: 0.0774 - accuracy: 0.9773 - val_loss: 0.1417 - val_accuracy: 0.9682 - 85s/epoch - 65ms/step


Epoch 18/25


1320/1320 - 85s - loss: 0.0757 - accuracy: 0.9777 - val_loss: 0.1493 - val_accuracy: 0.9659 - 85s/epoch - 65ms/step


Epoch 19/25


1320/1320 - 85s - loss: 0.0723 - accuracy: 0.9793 - val_loss: 0.1548 - val_accuracy: 0.9666 - 85s/epoch - 65ms/step


Epoch 20/25


1320/1320 - 85s - loss: 0.0696 - accuracy: 0.9797 - val_loss: 0.1456 - val_accuracy: 0.9679 - 85s/epoch - 65ms/step


Epoch 21/25


1320/1320 - 85s - loss: 0.0689 - accuracy: 0.9804 - val_loss: 0.1630 - val_accuracy: 0.9655 - 85s/epoch - 65ms/step


Epoch 22/25


1320/1320 - 85s - loss: 0.0651 - accuracy: 0.9812 - val_loss: 0.1399 - val_accuracy: 0.9677 - 85s/epoch - 65ms/step


Epoch 23/25


1320/1320 - 85s - loss: 0.0623 - accuracy: 0.9818 - val_loss: 0.1429 - val_accuracy: 0.9664 - 85s/epoch - 65ms/step


Epoch 24/25


1320/1320 - 85s - loss: 0.0615 - accuracy: 0.9825 - val_loss: 0.1314 - val_accuracy: 0.9697 - 85s/epoch - 65ms/step


Epoch 25/25


1320/1320 - 85s - loss: 0.0586 - accuracy: 0.9829 - val_loss: 0.1363 - val_accuracy: 0.9712 - 85s/epoch - 65ms/step


660/660 - 6s - loss: 0.1363 - accuracy: 0.9712 - 6s/epoch - 10ms/step



Fold 1 - Test Accuracy: 97.12%

Training on Fold 2/5


Model built successfully.


Epoch 1/25


1320/1320 - 92s - loss: 0.8636 - accuracy: 0.7805 - val_loss: 0.3712 - val_accuracy: 0.9027 - 92s/epoch - 70ms/step


Epoch 2/25


1320/1320 - 85s - loss: 0.3455 - accuracy: 0.9074 - val_loss: 0.2261 - val_accuracy: 0.9386 - 85s/epoch - 65ms/step


Epoch 3/25


1320/1320 - 85s - loss: 0.2641 - accuracy: 0.9264 - val_loss: 0.1917 - val_accuracy: 0.9494 - 85s/epoch - 65ms/step


Epoch 4/25


1320/1320 - 85s - loss: 0.2152 - accuracy: 0.9397 - val_loss: 0.2051 - val_accuracy: 0.9432 - 85s/epoch - 65ms/step


Epoch 5/25


1320/1320 - 85s - loss: 0.1877 - accuracy: 0.9470 - val_loss: 0.1741 - val_accuracy: 0.9522 - 85s/epoch - 65ms/step


Epoch 6/25


1320/1320 - 85s - loss: 0.1653 - accuracy: 0.9525 - val_loss: 0.1616 - val_accuracy: 0.9573 - 85s/epoch - 65ms/step


Epoch 7/25


1320/1320 - 85s - loss: 0.1459 - accuracy: 0.9573 - val_loss: 0.1946 - val_accuracy: 0.9483 - 85s/epoch - 65ms/step


Epoch 8/25


1320/1320 - 85s - loss: 0.1315 - accuracy: 0.9620 - val_loss: 0.1540 - val_accuracy: 0.9601 - 85s/epoch - 65ms/step


Epoch 9/25


1320/1320 - 85s - loss: 0.1191 - accuracy: 0.9657 - val_loss: 0.1520 - val_accuracy: 0.9609 - 85s/epoch - 65ms/step


Epoch 10/25


1320/1320 - 85s - loss: 0.1133 - accuracy: 0.9672 - val_loss: 0.1561 - val_accuracy: 0.9608 - 85s/epoch - 65ms/step


Epoch 11/25


1320/1320 - 85s - loss: 0.1060 - accuracy: 0.9692 - val_loss: 0.1570 - val_accuracy: 0.9592 - 85s/epoch - 65ms/step


Epoch 12/25


1320/1320 - 85s - loss: 0.0966 - accuracy: 0.9718 - val_loss: 0.1494 - val_accuracy: 0.9623 - 85s/epoch - 65ms/step


Epoch 13/25


1320/1320 - 85s - loss: 0.0912 - accuracy: 0.9739 - val_loss: 0.1332 - val_accuracy: 0.9664 - 85s/epoch - 65ms/step


Epoch 14/25


1320/1320 - 85s - loss: 0.0881 - accuracy: 0.9739 - val_loss: 0.1401 - val_accuracy: 0.9645 - 85s/epoch - 65ms/step


Epoch 15/25


1320/1320 - 85s - loss: 0.0828 - accuracy: 0.9758 - val_loss: 0.1458 - val_accuracy: 0.9647 - 85s/epoch - 65ms/step


Epoch 16/25


1320/1320 - 85s - loss: 0.0810 - accuracy: 0.9762 - val_loss: 0.1623 - val_accuracy: 0.9613 - 85s/epoch - 65ms/step


Epoch 17/25


1320/1320 - 85s - loss: 0.0764 - accuracy: 0.9777 - val_loss: 0.1390 - val_accuracy: 0.9674 - 85s/epoch - 65ms/step


Epoch 18/25


1320/1320 - 85s - loss: 0.0734 - accuracy: 0.9788 - val_loss: 0.1416 - val_accuracy: 0.9659 - 85s/epoch - 65ms/step


Epoch 19/25


1320/1320 - 85s - loss: 0.0723 - accuracy: 0.9795 - val_loss: 0.1343 - val_accuracy: 0.9679 - 85s/epoch - 65ms/step


Epoch 20/25


1320/1320 - 85s - loss: 0.0679 - accuracy: 0.9798 - val_loss: 0.1422 - val_accuracy: 0.9669 - 85s/epoch - 65ms/step


Epoch 21/25


1320/1320 - 85s - loss: 0.0676 - accuracy: 0.9808 - val_loss: 0.1361 - val_accuracy: 0.9675 - 85s/epoch - 65ms/step


Epoch 22/25


1320/1320 - 85s - loss: 0.0641 - accuracy: 0.9810 - val_loss: 0.1366 - val_accuracy: 0.9697 - 85s/epoch - 65ms/step


Epoch 23/25


1320/1320 - 85s - loss: 0.0604 - accuracy: 0.9827 - val_loss: 0.1313 - val_accuracy: 0.9696 - 85s/epoch - 65ms/step


Epoch 24/25


1320/1320 - 85s - loss: 0.0605 - accuracy: 0.9823 - val_loss: 0.1376 - val_accuracy: 0.9674 - 85s/epoch - 65ms/step


Epoch 25/25


1320/1320 - 85s - loss: 0.0609 - accuracy: 0.9830 - val_loss: 0.1314 - val_accuracy: 0.9685 - 85s/epoch - 65ms/step


660/660 - 6s - loss: 0.1314 - accuracy: 0.9685 - 6s/epoch - 9ms/step



Fold 2 - Test Accuracy: 96.85%

Training on Fold 3/5


Model built successfully.


Epoch 1/25


1320/1320 - 93s - loss: 0.8232 - accuracy: 0.7906 - val_loss: 0.3107 - val_accuracy: 0.9130 - 93s/epoch - 70ms/step


Epoch 2/25


1320/1320 - 85s - loss: 0.3353 - accuracy: 0.9097 - val_loss: 0.2209 - val_accuracy: 0.9402 - 85s/epoch - 65ms/step


Epoch 3/25


1320/1320 - 85s - loss: 0.2600 - accuracy: 0.9291 - val_loss: 0.1975 - val_accuracy: 0.9448 - 85s/epoch - 65ms/step


Epoch 4/25


1320/1320 - 85s - loss: 0.2091 - accuracy: 0.9426 - val_loss: 0.1568 - val_accuracy: 0.9607 - 85s/epoch - 65ms/step


Epoch 5/25


1320/1320 - 85s - loss: 0.1848 - accuracy: 0.9476 - val_loss: 0.1558 - val_accuracy: 0.9587 - 85s/epoch - 65ms/step


Epoch 6/25


1320/1320 - 85s - loss: 0.1604 - accuracy: 0.9545 - val_loss: 0.1589 - val_accuracy: 0.9578 - 85s/epoch - 65ms/step


Epoch 7/25


1320/1320 - 85s - loss: 0.1438 - accuracy: 0.9590 - val_loss: 0.1393 - val_accuracy: 0.9632 - 85s/epoch - 65ms/step


Epoch 8/25


1320/1320 - 85s - loss: 0.1325 - accuracy: 0.9622 - val_loss: 0.1377 - val_accuracy: 0.9656 - 85s/epoch - 64ms/step


Epoch 9/25


1320/1320 - 85s - loss: 0.1216 - accuracy: 0.9652 - val_loss: 0.1394 - val_accuracy: 0.9631 - 85s/epoch - 65ms/step


Epoch 10/25


1320/1320 - 85s - loss: 0.1116 - accuracy: 0.9686 - val_loss: 0.1349 - val_accuracy: 0.9655 - 85s/epoch - 65ms/step


Epoch 11/25


1320/1320 - 85s - loss: 0.1050 - accuracy: 0.9690 - val_loss: 0.1359 - val_accuracy: 0.9657 - 85s/epoch - 64ms/step


Epoch 12/25


1320/1320 - 85s - loss: 0.0978 - accuracy: 0.9720 - val_loss: 0.1316 - val_accuracy: 0.9670 - 85s/epoch - 65ms/step


Epoch 13/25


1320/1320 - 85s - loss: 0.0921 - accuracy: 0.9738 - val_loss: 0.1489 - val_accuracy: 0.9636 - 85s/epoch - 64ms/step


Epoch 14/25


1320/1320 - 85s - loss: 0.0882 - accuracy: 0.9741 - val_loss: 0.1329 - val_accuracy: 0.9686 - 85s/epoch - 65ms/step


Epoch 15/25


1320/1320 - 85s - loss: 0.0820 - accuracy: 0.9760 - val_loss: 0.1479 - val_accuracy: 0.9664 - 85s/epoch - 65ms/step


Epoch 16/25


1320/1320 - 85s - loss: 0.0816 - accuracy: 0.9766 - val_loss: 0.1368 - val_accuracy: 0.9661 - 85s/epoch - 64ms/step


Epoch 17/25


1320/1320 - 85s - loss: 0.0762 - accuracy: 0.9781 - val_loss: 0.1351 - val_accuracy: 0.9679 - 85s/epoch - 64ms/step


Epoch 18/25


1320/1320 - 85s - loss: 0.0743 - accuracy: 0.9789 - val_loss: 0.1363 - val_accuracy: 0.9680 - 85s/epoch - 64ms/step


Epoch 19/25


1320/1320 - 85s - loss: 0.0723 - accuracy: 0.9791 - val_loss: 0.1380 - val_accuracy: 0.9677 - 85s/epoch - 64ms/step


Epoch 20/25


1320/1320 - 85s - loss: 0.0712 - accuracy: 0.9799 - val_loss: 0.1645 - val_accuracy: 0.9615 - 85s/epoch - 65ms/step


Epoch 21/25


1320/1320 - 85s - loss: 0.0652 - accuracy: 0.9811 - val_loss: 0.1370 - val_accuracy: 0.9665 - 85s/epoch - 64ms/step


Epoch 22/25


1320/1320 - 85s - loss: 0.0647 - accuracy: 0.9812 - val_loss: 0.1296 - val_accuracy: 0.9680 - 85s/epoch - 65ms/step


Epoch 23/25


1320/1320 - 85s - loss: 0.0607 - accuracy: 0.9825 - val_loss: 0.1343 - val_accuracy: 0.9691 - 85s/epoch - 64ms/step


Epoch 24/25


1320/1320 - 85s - loss: 0.0603 - accuracy: 0.9826 - val_loss: 0.1455 - val_accuracy: 0.9685 - 85s/epoch - 64ms/step


Epoch 25/25


1320/1320 - 85s - loss: 0.0594 - accuracy: 0.9830 - val_loss: 0.1267 - val_accuracy: 0.9714 - 85s/epoch - 64ms/step


660/660 - 6s - loss: 0.1267 - accuracy: 0.9714 - 6s/epoch - 9ms/step



Fold 3 - Test Accuracy: 97.14%

Training on Fold 4/5


Model built successfully.


Epoch 1/25


1320/1320 - 93s - loss: 0.8711 - accuracy: 0.7774 - val_loss: 0.2938 - val_accuracy: 0.9223 - 93s/epoch - 71ms/step


Epoch 2/25


1320/1320 - 85s - loss: 0.3433 - accuracy: 0.9072 - val_loss: 0.2233 - val_accuracy: 0.9408 - 85s/epoch - 65ms/step


Epoch 3/25


1320/1320 - 85s - loss: 0.2639 - accuracy: 0.9270 - val_loss: 0.2648 - val_accuracy: 0.9277 - 85s/epoch - 65ms/step


Epoch 4/25


1320/1320 - 85s - loss: 0.2167 - accuracy: 0.9404 - val_loss: 0.2001 - val_accuracy: 0.9452 - 85s/epoch - 65ms/step


Epoch 5/25


1320/1320 - 85s - loss: 0.1877 - accuracy: 0.9475 - val_loss: 0.1586 - val_accuracy: 0.9574 - 85s/epoch - 65ms/step


Epoch 6/25


1320/1320 - 85s - loss: 0.1644 - accuracy: 0.9532 - val_loss: 0.1657 - val_accuracy: 0.9570 - 85s/epoch - 65ms/step


Epoch 7/25


1320/1320 - 85s - loss: 0.1473 - accuracy: 0.9579 - val_loss: 0.1891 - val_accuracy: 0.9527 - 85s/epoch - 65ms/step


Epoch 8/25


1320/1320 - 85s - loss: 0.1354 - accuracy: 0.9606 - val_loss: 0.1551 - val_accuracy: 0.9583 - 85s/epoch - 65ms/step


Epoch 9/25


1320/1320 - 85s - loss: 0.1219 - accuracy: 0.9645 - val_loss: 0.1555 - val_accuracy: 0.9624 - 85s/epoch - 65ms/step


Epoch 10/25


1320/1320 - 85s - loss: 0.1135 - accuracy: 0.9675 - val_loss: 0.1396 - val_accuracy: 0.9636 - 85s/epoch - 65ms/step


Epoch 11/25


1320/1320 - 85s - loss: 0.1048 - accuracy: 0.9697 - val_loss: 0.1419 - val_accuracy: 0.9633 - 85s/epoch - 65ms/step


Epoch 12/25


1320/1320 - 85s - loss: 0.1033 - accuracy: 0.9707 - val_loss: 0.1397 - val_accuracy: 0.9651 - 85s/epoch - 65ms/step


Epoch 13/25


1320/1320 - 85s - loss: 0.0925 - accuracy: 0.9734 - val_loss: 0.1559 - val_accuracy: 0.9606 - 85s/epoch - 65ms/step


Epoch 14/25


1320/1320 - 85s - loss: 0.0900 - accuracy: 0.9741 - val_loss: 0.1319 - val_accuracy: 0.9672 - 85s/epoch - 65ms/step


Epoch 15/25


1320/1320 - 85s - loss: 0.0848 - accuracy: 0.9757 - val_loss: 0.1724 - val_accuracy: 0.9563 - 85s/epoch - 64ms/step


Epoch 16/25


1320/1320 - 85s - loss: 0.0817 - accuracy: 0.9763 - val_loss: 0.1441 - val_accuracy: 0.9659 - 85s/epoch - 65ms/step


Epoch 17/25


1320/1320 - 85s - loss: 0.0748 - accuracy: 0.9782 - val_loss: 0.1424 - val_accuracy: 0.9674 - 85s/epoch - 65ms/step


Epoch 18/25


1320/1320 - 85s - loss: 0.0741 - accuracy: 0.9788 - val_loss: 0.1487 - val_accuracy: 0.9665 - 85s/epoch - 64ms/step


Epoch 19/25


1320/1320 - 85s - loss: 0.0726 - accuracy: 0.9789 - val_loss: 0.1429 - val_accuracy: 0.9665 - 85s/epoch - 64ms/step


Epoch 20/25


1320/1320 - 85s - loss: 0.0697 - accuracy: 0.9802 - val_loss: 0.1442 - val_accuracy: 0.9682 - 85s/epoch - 65ms/step


Epoch 21/25


1320/1320 - 85s - loss: 0.0646 - accuracy: 0.9815 - val_loss: 0.1357 - val_accuracy: 0.9703 - 85s/epoch - 65ms/step


Epoch 22/25


1320/1320 - 85s - loss: 0.0635 - accuracy: 0.9815 - val_loss: 0.1345 - val_accuracy: 0.9697 - 85s/epoch - 65ms/step


In [ ]:
import pickle
import numpy as np
def LoadDataNoDefOW_Evaluation():

    print("Loading non-defended dataset for open-world scenario for evaluation")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)
    try:
        # Load testing data
        with open(dataset_dir + 'X_test_Mon_NoDef.pkl', 'rb') as handle:
            X_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Mon_NoDef.pkl', 'rb') as handle:
            y_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'X_test_Unmon_NoDef.pkl', 'rb') as handle:
            X_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Unmon_NoDef.pkl', 'rb') as handle:
            y_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))

        X_test_Mon = np.array(X_test_Mon)
        y_test_Mon = np.array(y_test_Mon)
        X_test_Unmon = np.array(X_test_Unmon)
        y_test_Unmon = np.array(y_test_Unmon)

        return X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon

    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load evaluation data
LoadDataNoDefOW_Evaluation()

In [ ]:
from keras.models import load_model
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def Prediction(trained_model = None, dataset = None):
    X_test_Mon = dataset['X_test_Mon'].astype('float32')
    X_test_Unmon = dataset['X_test_Unmon'].astype('float32')
    print ("Total testing data ", len(X_test_Mon) + len(X_test_Unmon))
    X_test_Mon = X_test_Mon[:, :, np.newaxis]
    X_test_Unmon = X_test_Unmon[:, :, np.newaxis]
    result_Mon = trained_model.predict(X_test_Mon, verbose=2)
    result_Unmon = trained_model.predict(X_test_Unmon, verbose=2)
    return result_Mon, result_Unmon
def Evaluation(threshold_val = None, monitored_label = None,
                   unmonitored_label = None, result_Mon = None,
                   result_Unmon = None, log_file = None):
    print ("Testing with threshold = ", threshold_val)
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    # ==============================================================
    # Test with Monitored testing instances
    # evaluation
    for i in range(len(result_Mon)):
        sm_vector = result_Mon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Monitored
                TP = TP + 1
            else: # predicted as Unmonitored and actual site is Monitored
                FN = FN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Monitored
            FN = FN + 1

    # ==============================================================
    # Test with Unmonitored testing instances
    # evaluation
    for i in range(len(result_Unmon)):
        sm_vector = result_Unmon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Unmonitored
                FP = FP + 1
            else: # predicted as Unmonitored and actual site is Unmonitored
                TN = TN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Unmonitored
            TN = TN + 1
            
    print ("TP : ", TP)
    print ("FP : ", FP)
    print ("TN : ", TN)
    print ("FN : ", FN)
    print ("Total  : ", TP + FP + TN + FN)
    TPR = float(TP) / (TP + FN)
    print ("TPR : ", TPR)
    FPR = float(FP) / (FP + TN)
    print ("FPR : ",  FPR)
    Precision = float(TP) / (TP + FP)
    print ("Precision : ", Precision)
    Recall = float(TP) / (TP + FN)
    print ("Recall : ", Recall)
    print ("\n")
    log_file.writelines("%.6f,%d,%d,%d,%d,%.6f,%.6f,%.6f,%.6f\n"%(threshold_val, TP, FP, TN, FN, TPR, FPR, Precision, Recall))

# The evaluation of Open World scenario
def OW_Evaluation():
    evaluation_type = 'OpenWorld_NoDef'
    print("Evaluation type: ", evaluation_type)

    # Create the 'results' directory if it doesn't exist
    results_dir = '../results/'
    os.makedirs(results_dir, exist_ok=True)

    threshold = 1.0 - 1 / np.logspace(0.05, 2, num=15, endpoint=True)
    file_name = f'{results_dir}{evaluation_type}.csv'
    log_file = open(file_name, "w")  # Open the file in text mode, not binary mode
    # Load data
    dataset = {}
    model_name = ''
    print ("Loading data ...")
    #from utility import LoadDataNoDefOW_Evaluation
    X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon = LoadDataNoDefOW_Evaluation()
    # Load pre-trained model saved from 'Open_World_DF_***_Training.py'
    #model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
    model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'


    dataset['X_test_Mon'] = X_test_Mon
    dataset['y_test_Mon'] = y_test_Mon
    dataset['X_test_Unmon'] = X_test_Unmon
    dataset['y_test_Unmon'] = y_test_Unmon

    print ("Data loaded!")
    print ("Loading DF model ...")
    print ("The log file will be saved at ", file_name)
    print ("-- The log file will contains")
    print ("-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold")
    print ("-- These results will be used to plot the ROC or Precision&Recall Graph")
    trained_model = load_model(model_name)
    print ("Model loaded!")
    print ("Evaluation Type: ", evaluation_type)
    print ("Use the model from ", model_name)
    result_Mon, result_Unmon = Prediction(trained_model = trained_model, dataset = dataset)
    monitored_label = list(y_test_Mon)
    unmonitored_label = list(y_test_Unmon)
    log_file.writelines("%s,%s,%s,%s,%s,%s  ,%s  ,  %s, %s\n" % ('Threshold', 'TP', 'FP', 'TN', 'FN', 'TPR', 'FPR', 'Precision', 'Recall'))
    for th in threshold:
        Evaluation(threshold_val = th, monitored_label = monitored_label,
                   unmonitored_label = unmonitored_label, result_Mon = result_Mon,
                   result_Unmon = result_Unmon, log_file = log_file)
    log_file.close()  

OW_Evaluation()

ReLU besst approach

In [ ]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.5, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataNoDefOW_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


    # Compile the model
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs=20, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
   


    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
saved_path_keras = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
model.save(saved_path_keras)

print("Trained model saved successfully at:", saved_path_keras)


In [ ]:
# Load data for non-defended dataset for OW evaluation
import pickle
import numpy as np
def LoadDataNoDefOW_Evaluation():

    print("Loading non-defended dataset for open-world scenario for evaluation")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)
    try:
        # Load testing data
        with open(dataset_dir + 'X_test_Mon_NoDef.pkl', 'rb') as handle:
            X_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Mon_NoDef.pkl', 'rb') as handle:
            y_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'X_test_Unmon_NoDef.pkl', 'rb') as handle:
            X_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Unmon_NoDef.pkl', 'rb') as handle:
            y_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))

        X_test_Mon = np.array(X_test_Mon)
        y_test_Mon = np.array(y_test_Mon)
        X_test_Unmon = np.array(X_test_Unmon)
        y_test_Unmon = np.array(y_test_Unmon)

        return X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon

    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load evaluation data
LoadDataNoDefOW_Evaluation()

In [ ]:
from keras.models import load_model
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def Prediction(trained_model = None, dataset = None):
    X_test_Mon = dataset['X_test_Mon'].astype('float32')
    X_test_Unmon = dataset['X_test_Unmon'].astype('float32')
    print ("Total testing data ", len(X_test_Mon) + len(X_test_Unmon))
    X_test_Mon = X_test_Mon[:, :, np.newaxis]
    X_test_Unmon = X_test_Unmon[:, :, np.newaxis]
    result_Mon = trained_model.predict(X_test_Mon, verbose=2)
    result_Unmon = trained_model.predict(X_test_Unmon, verbose=2)
    return result_Mon, result_Unmon
def Evaluation(threshold_val = None, monitored_label = None,
                   unmonitored_label = None, result_Mon = None,
                   result_Unmon = None, log_file = None):
    print ("Testing with threshold = ", threshold_val)
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    # ==============================================================
    # Test with Monitored testing instances
    # evaluation
    for i in range(len(result_Mon)):
        sm_vector = result_Mon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Monitored
                TP = TP + 1
            else: # predicted as Unmonitored and actual site is Monitored
                FN = FN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Monitored
            FN = FN + 1

    # ==============================================================
    # Test with Unmonitored testing instances
    # evaluation
    for i in range(len(result_Unmon)):
        sm_vector = result_Unmon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Unmonitored
                FP = FP + 1
            else: # predicted as Unmonitored and actual site is Unmonitored
                TN = TN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Unmonitored
            TN = TN + 1
            
    print ("TP : ", TP)
    print ("FP : ", FP)
    print ("TN : ", TN)
    print ("FN : ", FN)
    print ("Total  : ", TP + FP + TN + FN)
    TPR = float(TP) / (TP + FN)
    print ("TPR : ", TPR)
    FPR = float(FP) / (FP + TN)
    print ("FPR : ",  FPR)
    Precision = float(TP) / (TP + FP)
    print ("Precision : ", Precision)
    Recall = float(TP) / (TP + FN)
    print ("Recall : ", Recall)
    print ("\n")
    log_file.writelines("%.6f,%d,%d,%d,%d,%.6f,%.6f,%.6f,%.6f\n"%(threshold_val, TP, FP, TN, FN, TPR, FPR, Precision, Recall))

# The evaluation of Open World scenario
def OW_Evaluation():
    evaluation_type = 'OpenWorld_NoDef'
    print("Evaluation type: ", evaluation_type)

    # Create the 'results' directory if it doesn't exist
    results_dir = '../results/'
    os.makedirs(results_dir, exist_ok=True)

    threshold = 1.0 - 1 / np.logspace(0.05, 2, num=15, endpoint=True)
    file_name = f'{results_dir}{evaluation_type}.csv'
    log_file = open(file_name, "w")  # Open the file in text mode, not binary mode
    # Load data
    dataset = {}
    model_name = ''
    print ("Loading data ...")
    #from utility import LoadDataNoDefOW_Evaluation
    X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon = LoadDataNoDefOW_Evaluation()
    # Load pre-trained model saved from 'Open_World_DF_***_Training.py'
    #model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
    model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'


    dataset['X_test_Mon'] = X_test_Mon
    dataset['y_test_Mon'] = y_test_Mon
    dataset['X_test_Unmon'] = X_test_Unmon
    dataset['y_test_Unmon'] = y_test_Unmon

    print ("Data loaded!")
    print ("Loading DF model ...")
    print ("The log file will be saved at ", file_name)
    print ("-- The log file will contains")
    print ("-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold")
    print ("-- These results will be used to plot the ROC or Precision&Recall Graph")
    trained_model = load_model(model_name)
    print ("Model loaded!")
    print ("Evaluation Type: ", evaluation_type)
    print ("Use the model from ", model_name)
    result_Mon, result_Unmon = Prediction(trained_model = trained_model, dataset = dataset)
    monitored_label = list(y_test_Mon)
    unmonitored_label = list(y_test_Unmon)
    log_file.writelines("%s,%s,%s,%s,%s,%s  ,%s  ,  %s, %s\n" % ('Threshold', 'TP', 'FP', 'TN', 'FN', 'TPR', 'FPR', 'Precision', 'Recall'))
    for th in threshold:
        Evaluation(threshold_val = th, monitored_label = monitored_label,
                   unmonitored_label = unmonitored_label, result_Mon = result_Mon,
                   result_Unmon = result_Unmon, log_file = log_file)
    log_file.close()  

OW_Evaluation()

//practice with Relu//.7/.5/.5

best approach

In [ ]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataNoDefOW_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_NoDef.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_NoDef.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_NoDef.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_NoDef.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataNoDefOW_Training()


In [ ]:
import numpy as np
import tensorflow as tf
import pickle
import numpy as np  # Add this line
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ELU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models

# Load data for non-defended dataset for OW training
def LoadDataNoDefOW_Training():

    print("Loading non-defended dataset for open-world scenario for training")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    try:
        # Load training data
        with open(dataset_dir + 'X_train_NoDef.pkl', 'rb') as handle:
            X_train = np.array(pickle.load(handle, encoding='latin1'))
        print("X_train loaded")
        with open(dataset_dir + 'y_train_NoDef.pkl', 'rb') as handle:
            y_train = np.array(pickle.load(handle, encoding='latin1'))
        print("y_train loaded")

        # Load validation data
        with open(dataset_dir + 'X_valid_NoDef.pkl', 'rb') as handle:
            X_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("X_valid loaded")
        with open(dataset_dir + 'y_valid_NoDef.pkl', 'rb') as handle:
            y_valid = np.array(pickle.load(handle, encoding='latin1'))
        print("y_valid loaded")

        print("Data dimensions:")
        print("X: Training data's shape : ", X_train.shape)
        print("y: Training data's shape : ", y_train.shape)
        print("X: Validation data's shape : ", X_valid.shape)
        print("y: Validation data's shape : ", y_valid.shape)
        
        print("Any None values in X_train:", np.any(np.isnan(X_train)))
        print("Any None values in y_train:", np.any(np.isnan(y_train)))
        print("Any None values in X_valid:", np.any(np.isnan(X_valid)))
        print("Any None values in y_valid:", np.any(np.isnan(y_valid)))
        
        # Merge datasets
        X_all = np.concatenate((X_train, X_valid), axis=0)
        y_all = np.concatenate((y_train, y_valid), axis=0)

        print("Merged data dimensions:")
        print("X: Merged data's shape : ", X_all.shape)
        print("y: Merged data's shape : ", y_all.shape)
        
        # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(X_all)
         # Print features of the merged dataset
        print("Features of the merged dataset:")
        print(y_all)
        
       
        return X_all, y_all


    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load, merge, and balance data
X_all, y_all = LoadDataNoDefOW_Training()


In [ ]:
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, BatchNormalization
from keras.layers import Activation, Flatten, Dense, Dropout, ReLU
from keras.initializers import glorot_uniform
from keras.optimizers import Adam
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from keras import layers, models
import numpy as np
from keras.layers import Activation

class DFNet:
    @staticmethod
    def build(input_shape, classes, dropout_rate1=0.5, dropout_rate2=0.5, dropout_rate_fc=0.7):
        model = Sequential()

        # ... (previous model definition remains unchanged)
        # Block 1
        filter_num = [None,32, 64, 128, 256]
        kernel_size = [None, 8, 8, 8, 8]
        conv_stride_size = [None, 1, 1, 1, 1]
        pool_stride_size = [None, 4, 4, 4, 4]
        pool_size = [None, 8, 8, 8, 8]

        for i in range(1, 4):
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             input_shape=input_shape if i == 1 else (None, input_shape[1]),
                             name=f'block{i}_conv1'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2 - 1}'))
            model.add(Activation('relu', name=f'block{i}_adv_act1'))
            model.add(Conv1D(filters=filter_num[i], kernel_size=kernel_size[i],
                             strides=conv_stride_size[i], padding='same',
                             name=f'block{i}_conv2'))
            model.add(BatchNormalization(name=f'batch_normalization_{i * 2}'))
            model.add(Activation('relu', name=f'block{i}_adv_act2'))

            model.add(MaxPooling1D(pool_size=pool_size[i], strides=pool_stride_size[i],
                                   padding='same', name=f'block{i}_pool'))
            model.add(Dropout(0.1, name=f'block{i}_dropout'))

        # ... (rest of the model remains unchanged)

        model.add(Flatten(name='flatten'))

        # Fully connected layers
        for i in range(1, 3):
            model.add(Dense(512, kernel_initializer=glorot_uniform(seed=0), name=f'fc{i}'))
            model.add(BatchNormalization(name=f'batch_normalization_{i + 8}'))
            model.add(Activation('relu', name=f'fc{i}_act'))

            # Experiment with different dropout rates
            model.add(Dropout(dropout_rate_fc, name=f'fc{i}_dropout'))

        # Output layer
        model.add(Dense(classes, kernel_initializer=glorot_uniform(seed=0), name='fc_final'))
        model.add(Activation('softmax', name="softmax"))

        print("Model built successfully.")
        return model
    # Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Build the model with the specified dropout rates
model = DFNet.build(input_shape=input_shape, classes=num_classes,
                    dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


# Print the model summary
print("Model Summary:")
model.summary()

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Assuming input_shape and num_classes are defined as follows (adjust based on your actual data)
input_shape = (5000, 1)
num_classes = 96

# Experiment with different dropout rates
dropout_rate1 = 0.6
dropout_rate2 = 0.5
dropout_rate_fc = 0.4

# Load and merge data using the function you defined
X_all, y_all = LoadDataNoDefOW_Training()
# Define the number of folds
n_splits = 5  # You can adjust this as needed

# Initialize Stratified K-Fold
stratkf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Lists to store results
all_histories = []

# Iterate over folds
for fold, (train_index, test_index) in enumerate(stratkf.split(X_all, y_all)):
    print(f"\nTraining on Fold {fold + 1}/{n_splits}")

    # Split the data
    X_train, X_test = X_all[train_index], X_all[test_index]
    y_train, y_test = y_all[train_index], y_all[test_index]
    
        # Build the model
    model = DFNet.build(input_shape=input_shape, classes=num_classes,
                        dropout_rate1=dropout_rate1, dropout_rate2=dropout_rate2, dropout_rate_fc=dropout_rate_fc)


    # Compile the model
    optimizer = Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
     # Define early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

    # Train the model with early stopping
    history = model.fit(X_train, y_train, epochs=20, batch_size=64, 
                        validation_data=(X_test, y_test), verbose=2, callbacks=[early_stopping])
    
   


    # Train the model
    #history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test), verbose=2)

    # Evaluate the model on the test set
    loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
    print(f"\nFold {fold + 1} - Test Accuracy: {accuracy * 100:.2f}%")

    # Save history for later analysis if needed
    all_histories.append(history)
    # Check unique labels in y_train
    
    # Update num_classes based on the actual number of unique classes in your dataset
#num_classes = len(np.unique(y_all))
saved_path_keras = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
model.save(saved_path_keras)

print("Trained model saved successfully at:", saved_path_keras)


In [ ]:
# Load data for non-defended dataset for OW evaluation
import pickle
import numpy as np
def LoadDataNoDefOW_Evaluation():

    print("Loading non-defended dataset for open-world scenario for evaluation")
    # Point to the directory storing data
    dataset_dir = '/kaggle/input/dataset-non-defended-open-world/'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)
    try:
        # Load testing data
        with open(dataset_dir + 'X_test_Mon_NoDef.pkl', 'rb') as handle:
            X_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Mon_NoDef.pkl', 'rb') as handle:
            y_test_Mon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'X_test_Unmon_NoDef.pkl', 'rb') as handle:
            X_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))
        with open(dataset_dir + 'y_test_Unmon_NoDef.pkl', 'rb') as handle:
            y_test_Unmon = np.array(pickle.load(handle, encoding='latin1'))

        X_test_Mon = np.array(X_test_Mon)
        y_test_Mon = np.array(y_test_Mon)
        X_test_Unmon = np.array(X_test_Unmon)
        y_test_Unmon = np.array(y_test_Unmon)

        return X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon

    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Call the function to load evaluation data
LoadDataNoDefOW_Evaluation()

In [ ]:
from keras.models import load_model
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def Prediction(trained_model = None, dataset = None):
    X_test_Mon = dataset['X_test_Mon'].astype('float32')
    X_test_Unmon = dataset['X_test_Unmon'].astype('float32')
    print ("Total testing data ", len(X_test_Mon) + len(X_test_Unmon))
    X_test_Mon = X_test_Mon[:, :, np.newaxis]
    X_test_Unmon = X_test_Unmon[:, :, np.newaxis]
    result_Mon = trained_model.predict(X_test_Mon, verbose=2)
    result_Unmon = trained_model.predict(X_test_Unmon, verbose=2)
    return result_Mon, result_Unmon
def Evaluation(threshold_val = None, monitored_label = None,
                   unmonitored_label = None, result_Mon = None,
                   result_Unmon = None, log_file = None):
    print ("Testing with threshold = ", threshold_val)
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    # ==============================================================
    # Test with Monitored testing instances
    # evaluation
    for i in range(len(result_Mon)):
        sm_vector = result_Mon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Monitored
                TP = TP + 1
            else: # predicted as Unmonitored and actual site is Monitored
                FN = FN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Monitored
            FN = FN + 1

    # ==============================================================
    # Test with Unmonitored testing instances
    # evaluation
    for i in range(len(result_Unmon)):
        sm_vector = result_Unmon[i]
        predicted_class = np.argmax(sm_vector)
        max_prob = max(sm_vector)

        if predicted_class in monitored_label: # predicted as Monitored
            if max_prob >= threshold_val: # predicted as Monitored and actual site is Unmonitored
                FP = FP + 1
            else: # predicted as Unmonitored and actual site is Unmonitored
                TN = TN + 1
        elif predicted_class in unmonitored_label: # predicted as Unmonitored and actual site is Unmonitored
            TN = TN + 1
            
    print ("TP : ", TP)
    print ("FP : ", FP)
    print ("TN : ", TN)
    print ("FN : ", FN)
    print ("Total  : ", TP + FP + TN + FN)
    TPR = float(TP) / (TP + FN)
    print ("TPR : ", TPR)
    FPR = float(FP) / (FP + TN)
    print ("FPR : ",  FPR)
    Precision = float(TP) / (TP + FP)
    print ("Precision : ", Precision)
    Recall = float(TP) / (TP + FN)
    print ("Recall : ", Recall)
    print ("\n")
    log_file.writelines("%.6f,%d,%d,%d,%d,%.6f,%.6f,%.6f,%.6f\n"%(threshold_val, TP, FP, TN, FN, TPR, FPR, Precision, Recall))

# The evaluation of Open World scenario
def OW_Evaluation():
    evaluation_type = 'OpenWorld_NoDef'
    print("Evaluation type: ", evaluation_type)

    # Create the 'results' directory if it doesn't exist
    results_dir = '../results/'
    os.makedirs(results_dir, exist_ok=True)

    threshold = 1.0 - 1 / np.logspace(0.05, 2, num=15, endpoint=True)
    file_name = f'{results_dir}{evaluation_type}.csv'
    log_file = open(file_name, "w")  # Open the file in text mode, not binary mode
    # Load data
    dataset = {}
    model_name = ''
    print ("Loading data ...")
    #from utility import LoadDataNoDefOW_Evaluation
    X_test_Mon, y_test_Mon, X_test_Unmon, y_test_Unmon = LoadDataNoDefOW_Evaluation()
    # Load pre-trained model saved from 'Open_World_DF_***_Training.py'
    #model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'
    model_name = '/kaggle/working/DFNet_OpenWorld_NoDef.keras'


    dataset['X_test_Mon'] = X_test_Mon
    dataset['y_test_Mon'] = y_test_Mon
    dataset['X_test_Unmon'] = X_test_Unmon
    dataset['y_test_Unmon'] = y_test_Unmon

    print ("Data loaded!")
    print ("Loading DF model ...")
    print ("The log file will be saved at ", file_name)
    print ("-- The log file will contains")
    print ("-- TP, FP, TN, FN, TPR, FPR, Precision, and Recall for each different threshold")
    print ("-- These results will be used to plot the ROC or Precision&Recall Graph")
    trained_model = load_model(model_name)
    print ("Model loaded!")
    print ("Evaluation Type: ", evaluation_type)
    print ("Use the model from ", model_name)
    result_Mon, result_Unmon = Prediction(trained_model = trained_model, dataset = dataset)
    monitored_label = list(y_test_Mon)
    unmonitored_label = list(y_test_Unmon)
    log_file.writelines("%s,%s,%s,%s,%s,%s  ,%s  ,  %s, %s\n" % ('Threshold', 'TP', 'FP', 'TN', 'FN', 'TPR', 'FPR', 'Precision', 'Recall'))
    for th in threshold:
        Evaluation(threshold_val = th, monitored_label = monitored_label,
                   unmonitored_label = unmonitored_label, result_Mon = result_Mon,
                   result_Unmon = result_Unmon, log_file = log_file)
    log_file.close()  

OW_Evaluation()

practice with other relu #method 2 